name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Check Version
        run: java -version && mvn -version && mvn help:effective-pom
      - name: Build application
        run: mvn package
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: menu-server
          path: target/menu-server.jar

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean
      - name: Run the Maven verify phase !
        run: mvn --batch-mode --update-snapshots verify

  coucou:
    runs-on: ubuntu-20.04
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: target/menu-server.jar
      - uses: actions/download-artifact@v2
        with:
          name: menu-server
          path: target/menu-server.jar